language: php
dist: trusty

matrix:
  include:
    - php: "5.2"
      dist: precise
      env: PHP52SUCKS=true
    - php: "5.3"
      dist: precise
    - php: "5.4"
    - php: "5.5"
    - php: "5.6"
    - php: "7.0"
    - php: "7.1"
    - php: "7.2"
    - php: "7.3"

install:
  - |
    if [[ $PHP52SUCKS == true ]]; then
      wget http://download.pear.php.net/package/Net_URL2-2.2.1.tgz
      pear install --offline ./Net_URL2-2.2.1.tgz
    else
      pear channel-update pear.php.net
      composer install --no-dev
    fi
  - |
    # Export Composer's global bin dir to PATH, but not on PHP 5.2 (borrowed from Wordpress):
    if [[ $PHP52SUCKS != true ]]; then
      composer config --list --global
      export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`
    fi
  - |
    # Global install of a supported PHPUnit version
    if [[ $PHP52SUCKS != true ]]; then
      composer global require "phpunit/phpunit=^3.7|^4.8|^5.7"
    fi

addons:
  hosts:
    - hr2.local
    - www.hr2.local

before_script:
  # directory for apache logs
  - mkdir -p $TRAVIS_BUILD_DIR/logs
  # As described @ http://docs.travis-ci.com/user/languages/php/#Apache-%2B-PHP
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-php5
  #- sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  #- sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  #- sudo a2enmod rewrite actions fastcgi alias
  #- echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  #- ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - |
    # configure apache virtual hosts
    if [[ $(phpenv version-name) == "5.2" || $(phpenv version-name) == "5.3" ]]; then
      sudo cp -f tests/travis-ci-apache /etc/apache2/sites-available/default
      sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
    else
      sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
      sudo cp -f tests/travis-ci-apache-24 /etc/apache2/sites-available/000-default.conf
      sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
    fi
  - sudo service apache2 restart
  # use travis config for network-backed tests
  - cp tests/NetworkConfig.php.travis tests/NetworkConfig.php

script:
  - which phpunit
  - phpunit --version
  # Do not test composer installation on PHP 5.2 due to lack of composer
  - if [[ $PHP52SUCKS != true ]]; then phpunit ./tests; fi
  - pear package-validate ./package.xml
  - php ./pear-package-helper.php
  - pear install ./.pear-package/package.xml
  - cp tests/NetworkConfig.php.travis `pear config-get test_dir`/HTTP_Request2/NetworkConfig.php
  - cd `pear config-get test_dir` && phpunit HTTP_Request2

after_failure:
  - cat $TRAVIS_BUILD_DIR/logs/hr2-error.log
  - cat $TRAVIS_BUILD_DIR/logs/hr2-access.log
